### PR TITLE
Feat implement send welcome email ruby

### PR DESCRIPTION
**Pull request by 1n40**
Implemented Welcome email feature in Ruby

### CODE REVIEW

**Comment by Meldiron** [comment]
@lohanidamodar Please review the code.

**Comment by 1n40** [comment]
@lohanidamodar Please check this PR.

**Review by Meldiron — CHANGES_REQUESTED** [review]
Please include a screenshot of successful execution and its output from Appwrite Console. Without that, we cannot proceed to merge the PR.

**Comment by 1n40** [comment]
@Meldiron please check [these](https://github.com/appwrite/demos-for-functions/pull/160/commits/8781e49b0d0bac2e207acb8ac5ec1a1e2b4ecabb?short_path=643957d#diff-643957d338f5d80ef6e2f677a9ccfe8c9cc2934bc1a637c1c0c8f1793535cca0) screenshots. If not these, then please can you show me a demo screenshot. Thank you.

**Comment by lohanidamodar** [comment]
> @Meldiron please check [these](https://github.com/appwrite/demos-for-functions/pull/160/commits/8781e49b0d0bac2e207acb8ac5ec1a1e2b4ecabb?short_path=643957d#diff-643957d338f5d80ef6e2f677a9ccfe8c9cc2934bc1a637c1c0c8f1793535cca0) screenshots. If not these, then please can you show me a demo screenshot. Thank you.

You should instead add the screenshot on the PR description not in the readme

**Comment by christyjacob4** [comment]
@1n40 closing this PR for now since there has been no activity in quite a long time. Feel free to reopen it when you're ready to start working on it once again. 🙂

**Pull request closed without merging**
