### PR TITLE
Feat implement backup to storage python

### PR DESCRIPTION
**Pull request by achintya-7**
Fixes : https://github.com/appwrite/appwrite/issues/1902

### CODE REVIEW

**Comment by achintya-7** [comment]
# Adding screenshots of the execution of the function in Appwrite
# Collections

Screenshot from 2021-10-14 21-05-18
Screenshot from 2021-10-14 21-05-21

# ENV varables

Screenshot from 2021-10-14 21-06-07

# Log Output

Screenshot from 2021-10-14 21-06-23

# Storage

Screenshot from 2021-10-14 21-06-48
## An example of the file
Screenshot from 2021-10-14 21-06-52

**Comment by achintya-7** [comment]
Issue : https://github.com/appwrite/appwrite/issues/1902

**Review by christyjacob4 — CHANGES_REQUESTED** [review]
python/backup-to-storage/requirments.txt

The file name is incorrect . It needs to be `requirements.txt`

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)

**Pull request merged**
