### PR TITLE
Feat implement generate giphy gif dart

### PR DESCRIPTION
**Pull request by 2002Bishwajeet**
Implements: [appwrite/appwrite#1922](https://github.com/appwrite/appwrite/issues/1922)

# Screenshots
image
image

### CODE REVIEW

**Comment by 2002Bishwajeet** [comment]
CC @Meldiron 
Also I have added some SS in the readme Files too, requested to go through them pls. It may be possible that one SS might be redundant. Just lemme know if it needs any changes 🙂

**Comment by idivyanshbansal** [comment]
> I can't click on this 😂. Also I couldn't see the tar file in my branch too. Is this a bug or something else? image
> 
> Also, we can raise more issues like updating the readme files of all functions with screenshots/gifs. This would give chance to new contributors

@2002Bishwajeet  I would love to do that 🙂

**Comment by 2002Bishwajeet** [comment]
> > I can't click on this 😂. Also I couldn't see the tar file in my branch too. Is this a bug or something else? image
> > Also, we can raise more issues like updating the readme files of all functions with screenshots/gifs. This would give chance to new contributors
> 
> @2002Bishwajeet I would love to do that 🙂

That's why I pitched the idea😉 to attract more beginner friendly issues for you all

**Comment by idivyanshbansal** [comment]
Thank you @2002Bishwajeet  🙌🙌

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)

**Pull request merged**
