### PR TITLE
Ruby implementation of generateBitlyUrl

### PR DESCRIPTION
**Pull request by foxy-eyed**
Related issue: https://github.com/appwrite/appwrite/issues/1903
Implement cloud function `generateBitlyUrl()` with Ruby.

### CODE REVIEW

**Review by Meldiron — CHANGES_REQUESTED** [review]
Great PR! 🤯 Left some comments during the review, please check them out.

**Comment by Meldiron** [comment]
@lohanidamodar Please review the code.

**Comment by lohanidamodar** [comment]
@foxy-eyed apart from the requests made by @Meldiron everything looks good. Great job 🚀

**Comment by foxy-eyed** [comment]
@Meldiron @lohanidamodar thanks for review! All done, please check out 🙌

**Review by lohanidamodar — APPROVED** [review]
@foxy-eyed Great work. Looks good to me. Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) to help make Appwrite better.

**Comment by foxy-eyed** [comment]
Hi, @Meldiron! Do you have any other suggestions or is it done?)
I fixed all previous and have approve from @lohanidamodar, but now PR is stuck because of your review status.
Could you please check again? Sorry for bothering)

**Review by Meldiron — APPROVED** [review]
Looks good to me.

**Comment by Meldiron** [comment]
THANK YOU! All changes merged 🥳

Please reach out to `eldadfux` on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)

**Pull request merged**
