### PR TITLE
Create Issue templates using GitHub Issue Forms

### PR DESCRIPTION
**Pull request by abxhr**
This PR creates Issue templates using the GitHub Issue Forms.

**Fixes** #99

### CODE REVIEW

**Review by lohanidamodar — CHANGES_REQUESTED** [review]
Thank you @abxhr for the PR 🙏🏻. Please use https://github.com/appwrite/appwrite issue templates as the reference and make the necessary changes to make it consistent.

**Comment by abxhr** [comment]
@lohanidamodar I have made the requested changes

**Comment by abxhr** [comment]
@lohanidamodar Sorry for the ping, but can this PR be reviewed? 😅

**Review by Meldiron — APPROVED** [review]
Looks good to me

**Comment by Meldiron** [comment]
THANK YOU! All changes merged 🥳

Please reach out to `eldadfux` on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)

**Pull request merged**
