### PR TITLE
Python implementation of get internet speed 

### LINKED ISSUE #89: Implement getInternetSpeed() Appwrite Function ⚡
# Introduction

Appwrite Functions allow you to extend and customize your Appwrite server functionality by executing your custom code 🤩 You can learn more at our official [Appwrite Functions docs](https://appwrite.io/docs/functions).

Your task is to implement `getInternetSpeed` function. You can look at the existing [Appwrite Functions demo](https://github.com/appwrite/demos-for-functions) in the coding language you prefer to see how it works.

This function should use any Speedtest provider to check the download and upload speed of the server. The results should be provided as an output of the function.

> Please make sure to store all configurable parameters as environment variables, so others can start using your script without having to edit it. If some data is different for each execution, make sure to use `APPWRITE_FUNCTION_EVENT_DATA` or `APPWRITE_FUNCTION_DATA` environment variable.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Create `feat-implement-get-internet-speed-X` branch where `X` is programming language you used
- [ ] Write code for the function
- [ ] Test the function using Appwrite
- [ ] Write a `README.md` explaining what function does, how to use and customize it. Here is [an example](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email).
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊 There are 9 languages in which you can implement this function. When requesting to be assigned, please mention which language would you like to use.

### Assignees table

✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

| Function / Language | Deno | NodeJS | PHP | Python | Ruby | Dart | .NET | Java | Kotlin |
| ------------------- | ---- | ------ | --- | ------ | ---- | ---- | ---- | ---- | ------ |
| getInternetSpeed            | ❌   | ❌     | ❌  | ❌     | ❌   | ❌   | ❌   | ❌   | ❌     |

**Happy Appwriting!**

### PR DESCRIPTION
**Pull request by Ares358**
Python implementation of getInternetSpeed to get the server's upload and download speed in Mbps
related to #89

### CODE REVIEW

**Review by Meldiron — COMMENTED** [review]
Great PR! 🤯 Please rename the folder from `getInternetSpeed` to `get-internet-speed` to stay consistent with the rest of the repo.

**Comment by Ares358** [comment]
> Great PR! 🤯 Please rename the folder from `getInternetSpeed` to `get-internet-speed` to stay consistent with the rest of the repo.

Done!

**Comment by christyjacob4** [comment]
@Ares358  Can you add screenshots of a successful execution from the Appwrite Dashboard ?

**Comment by christyjacob4** [comment]
@Ares358 Closing this PR for now since there has been no activity in a long time. Feel free to reopen it when you'd like to continue working on it.

**Pull request closed without merging**
